# This file is a submodule of ../build.sh.

build_srpm_help()
{
    echo
    echo build_srpm
    echo ----------
    echo "Builds the SRPM (source RPM) from the spec file and the"
    echo "source from github."
}

write_version_spec()
{
    cat >${RPMBUILD}/SOURCES/impala_version.spec <<EOF
# This file was generated by the Altiscale build_srpm stage
# of the impala RPM build.  It is included in impala.spec

%define impala_version ${IMPALA_VERSION}
%define buildnum ${BUILD_NUMBER}
%define impala_hadoop_version ${IMPALA_HADOOP_VERSION}
%define impala_hadoop_home ${IMPALA_HADOOP_HOME}
%define impala_hive_version ${IMPALA_HIVE_VERSION}
%define impala_hive_home ${IMPALA_HIVE_HOME}
EOF
}

build_srpm()
{
    if (($HELP)) ; then build_srpm_help ; return ; fi

    if [ -z "$RPMBUILD" ] ; then
	echo "build_srpm requires setup_rpmbuild"
	setup_rpmbuild
    fi

    # copy the spec file into place
    : ${SPEC_PATH:=${APPDIR}/spec/impala.spec}
    cp ${SPEC_PATH} ${RPMBUILD}/SPECS/
    cp ${APPDIR}/src/* ${RPMBUILD}/SOURCES/

    # generate the spec file with version information
    write_version_spec

    # copy the source into place
    pushd ${WORKSPACE}
    tar --exclude .git --exclude .gitignore -czf ${RPMBUILD}/SOURCES/${IMPALA_RELEASE}.tar.gz ${IMPALA_RELEASE}
    popd

    # build the source rpm
    rpmbuild \
	-vvv \
	-bs \
	--define "_topdir $RPMBUILD" \
	${RPMBUILD}/SPECS/impala.spec
}
